version: '3'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'dashboard'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - dashboard-db-vol:/var/lib/mysql
        networks:
            - backend
        restart: on-failure
    dashboard:
        build: .
        depends_on:
            - db
        ports:
            - "8080:8080"
        environment:
            MYSQL_HOST: 'db'
            MYSQL_DATABASE: 'dashboard'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
        networks:
            - backend
        restart: on-failure
networks:
    backend:
volumes:
    dashboard-db-vol:
